MMXApplication/Controllers/RaceResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MMXServiceInterfaceLib;
using MMXDataService;
using MMXModelsLib;
using System.Text;
using System.Web.UI;
using System.IO;

namespace MMXApplication.Controllers
{
    public class RaceResultController : BaseController {

        private IRaceService raceService;
        private IRaceClassMemberService raceClassMemberService;

        protected override void Initialize(System.Web.Routing.RequestContext requestContext) {
            base.Initialize(requestContext);
            if (raceService == null) {
                raceService = new RaceService();
            }
            if (raceClassMemberService == null) {
                raceClassMemberService = new RaceClassMemberService(); 
            }
        }

        
        [HttpPost]
        public ActionResult RaceResultsList(YearSelectorModel model) {
            if (model != null) {
                return RaceResultsList(model.CurrentYear);
            } else {
                return RaceResultsList();
            }
        }
        
        
        public ActionResult RaceResultsList(short year = 0) {
            SetTabClasses(resultsTab);
            RaceResultViewModel raceResultViewModel = new RaceResultViewModel();
            short resultYear = raceClassMemberService.GetCurrentEnrollmentYear();
            short enrollmentYear = resultYear;
            if (year > 0) {
                resultYear = year;
            }
            raceResultViewModel.Year = resultYear;
            raceResultViewModel.CompletedRaces = raceService.GetRacesWithResults(resultYear).ToList();
            //raceResultViewModel.RaceResults = new List<RaceResultModel>(); //raceService.GetAllRaceResults(resultYear);
            YearSelectorModel yearSelector = new YearSelectorModel();
            yearSelector.Years = GetYears(resultYear, enrollmentYear);
            raceResultViewModel.YearSelector = yearSelector;
            raceResultViewModel.IsAdminRole = base.IsAdminRole;
            //raceResultViewModel.RaceSelector = new RaceSelectorModel();
            //raceResultViewModel.RaceSelector.Races = raceService.GetYearsRaces(resultYear);
            return BaseView("RaceResultList", raceResultViewModel, "Race Results");
        }


        


        public ActionResult RaceClassDisplayList(int raceKey) {
            RaceClassDisplayListModel rcdlm = new RaceClassDisplayListModel(); 
            rcdlm.RaceClassDisplayModels  = raceService.GetRaceClassesForResults(raceKey).ToList();
            //rcdlm.RaceKey = raceKey;            
            return PartialView("RaceClassDisplayList", rcdlm);
        }

       
        //public ActionResult ShowClassRaceResult(int raceKey, int raceClassKey) {
        //    SetTabClasses(resultsTab);
        //    RaceResultModel model = raceService.GetClassRaceResult(raceKey, raceClassKey);            
        //    return BaseView("ClassRaceResult", model, "Class Results " + model.Track.TrackName);
        //}

        [Authorize]
        public ActionResult RaceResultEntry(int raceKey) {
            RaceResultEntryModel rreModel = new RaceResultEntryModel();
            rreModel.Race = raceService.GetRace(raceKey);
            rreModel.Classes = raceClassMemberService.GetAllRaceClasses().Models;
            rreModel.IsAdminRole = this.IsAdminRole;
            SetTabClasses(resultsTab);
            return BaseView("RaceResultEntry", rreModel, "Select Race Class");
        }


        [Authorize]
        [HttpPost]
        public ActionResult RaceResultEntry(RaceSelectorModel model) {
            if (model != null) {
                RaceResultEntryModel rreModel = new RaceResultEntryModel();
                rreModel.Race = raceService.GetRace(model.RaceKey);
                rreModel.Classes = raceClassMemberService.GetAllRaceClasses().Models;
                rreModel.IsAdminRole = this.IsAdminRole;
                SetTabClasses(resultsTab);
                return BaseView("RaceResultEntry", rreModel, "Select Race Class");
            } else {
                return RaceResultsList();
            }
        }

        [Authorize]
        public ActionResult AddUpdateRaceClassResults(int raceKey, int raceClassKey, int raceClassMemberKey = 0, int raceResultKey = 0, List<ErrorMessageModel> errors = null) {
            SetTabClasses(resultsTab);
            RaceClassResultEntryModel model = raceService.GetRaceResultEntryModel(raceKey, raceClassKey, raceResultKey);
            model.IsAdminRole = this.IsAdminRole;
            if (errors != null && errors.Count() > 0 &&  raceClassMemberKey > 0) {
                model.AddModelEntryErrors(raceClassMemberKey, errors);
            }
            return BaseView("AddUpdateRaceClassResults", model, "Add Update Results");

        }

        //[Authorize]
        //[HttpPost]
        //public ActionResult AddUpdateRaceClassResults(RaceClassResultEntryModel model) {            
        //    bool okEntries = true;
        //    // todo one at a time send via ajax update partial    
        //    int i = 0;
        //    foreach (MemberRaceResultEntryModel result in model.MemberResultEntries) {
        //        StringBuilder sb = new StringBuilder();
                
        //            if (ValidateEntry(result, sb)) {
        //                if (result.RaceResultKey < 1) {
        //                    result.RaceKey = model.Race.RaceKey;
        //                   // okEntries = raceService.CreateMemberRaceResult(result);
        //                } else {
        //                    // else update - result or details or both
        //                   // raceService.UpdateMemberRaceResultPosition(result.RaceResultKey, result.MotoOnePosition, result.StatusMotoOne, result.MotoTwoPosition, result.StatusMotoTwo, result.Overall);
        //                }
        //            } else {
        //                //model.MemberResultEntries[i].Error = sb.ToString();
        //                okEntries = false;
        //            }
                
        //        i++;
              
        //    }
        //    if (okEntries == false) {               
        //        return BaseView("AddUpdateRaceClassResults", model);
        //    } else {
        //        return RaceResultEntry(model.Race.RaceKey);
        //    }

        //}

        //[Authorize]
        //public ActionResult UpdateRaceClassResult(MemberRaceResultEntryModel model) {
        //    if (model.RaceResultKey > 0) {
        //        model.EntrySuccess = false;
        //        model.Errors.Clear();
        //    }
        //    return PartialView("MemberRaceResultEntryForm", model);
        //}


        [Authorize]
        [HttpPost]
        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public ActionResult AddUpdateRaceClassResult(MemberRaceResultEntryModel model) {
            bool isValidState = ValidateModelState(model);
            
            if (Request.IsAjaxRequest()) {
                string t = "blah";

            }
            
            if (!isValidState) {
                model.EntrySuccess = false;    
                
            } else {
                model.Errors.Clear();
                model.EntrySuccess = true;
                // todo capture business / data errors               
                raceService.CreateMemberRaceResult(model);
                // save fill data values
                // todo get values and show display and update button  
               //return AddUpdateRaceClassResults(model.RaceKey, model.RaceClassKey);
            }
            // todo include year??
            //return AddUpdateRaceClassResults(model.RaceKey, model.RaceClassKey, model.RaceClassMemberKey, model.RaceResultKey, model.Errors);
            return PartialView("MemberRaceResultEntryForm", model);
        }

        public ActionResult GetRaceClassResults(int raceKey, int raceClassKey) {
            List<RaceClassMemberResultModel> raceClassResults = raceService.GetRaceResultsForRaceClass(raceKey, raceClassKey).ToList();
            
            return PartialView("RaceClassResultsList", raceClassResults);
        }       

        public static List<SelectorKey> GetYears(short selectedYear, short enrollmentYear) {
            List<SelectorKey> years = new List<SelectorKey>();
            short startYear = enrollmentYear;
            while (startYear > 2006) {
                if (startYear != selectedYear) {
                    SelectorKey key = new SelectorKey() {
                        CurrentYear = startYear
                    };
                    years.Add(key);                   
                }
                startYear--;
            }
            return years;

        }

        private string uploadPath = "~/App_Data/MMXData";


        [Authorize]
        public ActionResult UploadResultFile(UploadRaceResultsViewModel uploadRaceResultsViewModel) {
            // todo set current year and next race
            //UploadRaceResultsViewModel uploadRaceResultsViewModel = new UploadRaceResultsViewModel();
             uploadRaceResultsViewModel.SelectedRaceModel = GetUploadRaceResultsModel(2012, 9);

            return PartialView("UploadResultFile", uploadRaceResultsViewModel);
        }

        [HttpPost]
        [Authorize]
        public ActionResult UploadResultFile(HttpPostedFileBase uploadFile, string worksheetName, int raceKey, int year) {
            SetTabClasses(applicationTab);
            var filePath = string.Empty;
            if (uploadFile == null || uploadFile.ContentLength <= 0) {
                // todo some error handling here
                return View();
            }

MMXApplication/Views/Shared/ErrorMessage.cshtml
@model IEnumerable<MMXModelsLib.ErrorMessageModel>
@foreach (var item in Model) {   
    <div class="display-field">
        @Html.DisplayFor(modelItem => item.ErrorMessage, new { @class = "errorformat" })
    </div>
}


MMXApplication/Views/Shared/RaceSelector.cshtml
@model MMXModelsLib.RaceSelectorModel
<div>
    <span>
        <text>Select a Race:</text>
        @if (Model.Races != null) {
            @Html.DropDownListFor(m => m.RaceKey, new SelectList(Model.Races, "RaceKey", "RaceName"))
        }
        <input type="submit" value="Go" />
    </span>
</div>

MMXApplication/Views/Shared/YearSelector.cshtml
@model MMXModelsLib.YearSelectorModel
<div>
    <span>
       <text>Select Another Year:</text>
        @if (Model.Years != null) {
            @Html.DropDownListFor(m => m.CurrentYear, new SelectList(Model.Years, "CurrentYear", "CurrentYear"))
        }
        <input type="submit" value="Go" />
    </span>
</div>

MMXApplication/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<!--[if IEMobile 7 ]><html class="no-js iem7 standalone"><![endif]-->
<!--[if (gt IEMobile 7)|!(IEMobile)]><html class="no-js "><!--<![endif]-->
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/MobileStyle.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>MastersMX</h1>
            </div>            
        </div>
        <div id="main">              
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

MMXApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IEMobile 7 ]><html class="no-js iem7 standalone"><![endif]-->
<!--[if (gt IEMobile 7)|!(IEMobile)]><html class="no-js "><!--<![endif]-->
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("../../Content/MobileStyle.css")" rel="stylesheet" type="text/css" />
    <link href="../../Content/themes/base/jquery.ui.base.css" rel="stylesheet" type="text/css" />
    <link href="../../Content/themes/base/jquery.ui.theme.css" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("../../Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("../../Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("../../Scripts/jquery-ui-1.8.11.js")" type="text/javascript"></script>
    <script src="@Url.Content("../../Scripts/jquery.ui.core.js")" type="text/javascript"></script>
    <script src="@Url.Content("../../Scripts/jquery.ui.dialog.js")" type="text/javascript"></script>   
    <script src="@Url.Content("../../Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("../../Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
    <script src="@Url.Content("../../Scripts/jquery.form.js")" type="text/javascript"></script>


    <script type="text/javascript">

        $(document).ready(function () {

            $('#SelectedRaceModel_CurrentYear').attr('disabled', false);
            $('#SelectedRaceModel_RaceKey').attr('disabled', false);
            $('#uploadForm').ajaxForm();

            $('.closebuttons').hide();
            $("#logOnDiv").dialog({ autoOpen: false, title: "Log On", modal: true, width: 'auto', height: 'auto' });
            $("#selectRaceResultUploadDiv").dialog({ autoOpen: false, title: "Select a Year then a Race", modal: true, width: 'auto', height: 'auto' });
            $("#fileUploadingDiv").dialog({ autoOpen: false, title: "File Upload", modal: true, width: 'auto', height: 'auto' });

            $("#mmxLogOnActionLink").click(function () {
                $("#logOnDiv").load(this.href, function () {
                    $("#logOnDiv").dialog("open");

                });
                return false;
            });

            $('#showAnotherYearAndRacesActionLink').click(function () {
                $('#selectRaceResultUploadDiv').load(this.href, function () {
                    $('#selectRaceResultUploadDiv').dialog('open');

                });
                return false;
            });



            $(window).resize(function () { $(".ui-dialog-content").dialog("option", "position", "center"); });

         

        });

            function postFailure() {
                alert("Failure");
            }

            function postSuccess(key, openId, closeId, rowId) {
                $("#" + closeId + key).show();
                $("#" + openId + key).hide();
                if (rowId != null) {
                    scrollTableToSelected(rowId + key);
                }

            }

            function postOnComplete() {
            }


            function closeDisplayDiv(key, resultcontainer, openId, closeId) {
                $("#" + resultcontainer + key).empty();
                $("#" + closeId + key).hide();
                $("#" + openId + key).show();
            }

            function scrollTableToSelected(selectedId) {
                var row = $('#' + selectedId).position();
                $('html, body').animate({ scrollTop: row.top }, 1000);
            }

            function SetYear() {
                var cKey = $("#SelectedRaceModel_CurrentYear").val();
                var rKey = 0;
                $.ajax({
                    url: '@Url.Action("SelectRaceResultUpload", "RaceResult")',
                    type: 'GET',
                    data: { year: cKey, raceKey: rKey },
                    success: function (result) {
                        $('#selectRaceResultUploadDiv').html(result);
                        $('#CurrentYear').attr('disabled', true);
                    }
                });
                return false;
            }


            function SetRace() {
                var cKey = $('#SelectedRaceModel_CurrentYear').val();
                var rKey = $('#SelectedRaceModel_RaceKey').val();

                $.ajax({
                    url: '@Url.Action("SelectedRaceUpload", "RaceResult")',
                    type: 'GET',
                    data: { year: cKey, raceKey: rKey },
                    success: function (result) {
                        closeSelectDialog('selectRaceResultUploadDiv')
                        $('#selectedraceuploaddiv').html(result);
                    }
                });
                return false;
            }

            function beginUpload(worksheet) {
                $('#fileUploadingDiv').load('<div>Loading...<span>' + worksheet + '</span></div>', function () {
                    $('#fileUploadingDiv').dialog('open');

                });

            }


            function uploadSucess() {
                closeSelectDialog('fileUploadingDiv');
            }

            function closeSelectDialog(dialogid) {
                $('#' + dialogid).dialog('close');
                return true;

            }
         


</script>
    
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>
                    MastersMX</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home", null, new { @class = (string)ViewData["mxtab"] })</li>
                    <li>@Html.ActionLink("Results", "RaceResultsList", "RaceResult", null, new { @class = (string)ViewData["resultstab"] })</li>
                    <li>@Html.ActionLink("Classes", "ShowActiveRaceClasses", "Race", null, new { @class = (string)ViewData["classestab"] })</li>
                    <li>@Html.ActionLink("Schedule", "RaceSchedule", "Race", null, new { @class = (string)ViewData["scheduleTab"] })</li>
                    <li>@Html.ActionLink("Members", "MemberList", "Member", null, new { @class = (string)ViewData["membertab"] })</li>
                    @if (Request.IsAuthenticated) {   
                        <li>@Html.ActionLink("Dashboard", "SuperUserDashboard", "RaceResult", null, new { @class = (string)ViewData["applicationtab"] })</li>
                    } else {
                        <li>@Html.ActionLink("Join", "MemberApplication", "Member", null, new { @class = (string)ViewData["applicationtab"] })</li>
                    }
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
            <div id="logOnDiv" style="background-color: #F5F5F5;">
            </div>          
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

MMXApplication/Views/Shared/_LogOnPartial.cshtml

@if (Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>! [ @Html.ActionLink("Log Off", "LogOff", "Account")
    ]</text>
} else {    
    <text><span>[ </span><a title="LogOnLink" href="/Account/LogOn" id="mmxLogOnActionLink">Log On</a><span> ]</span></text>
}